baseURL = "https://altamentecapaces.org"
title = "Altamente Capaces"

theme = "universal"

languageCode = "es-es"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "es"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
[pagination]
pagerSize = 10

# not pluralize title pages by default
pluralizelisttitles = false

[services]
# [services.disqus]
# Enable comments by entering your Disqus shortname
# Shortname = "devcows"
[services.googleAnalytics]
# Enable Google Analytics by entering your tracking code
id = ""

[params]
viewMorePostLink = "/blog/"
author = "Altamente Capaces"
defaultKeywords = ["Altas Capacidades", "Gifted", "Superdotado"]
mainSections = ["blog"]
defaultDescription = "Página web de Altamente Capaces"

# Social media
#facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
#twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
default_sharing_image = "/logo.png"

# Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
#enableGoogleMaps = true
#googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

# latitude = "-12.043333"
# longitude = "-77.028333"

# Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
style = "green"

# Since this template is static, the contact form uses www.formspree.io as a
# proxy. The form makes a POST request to their servers to send the actual
# email. Visitors can send up to a 50 emails each month for free.
#
# What you need to do for the setup?
#
# - register your account to https://formspree.io/register
# - login and create new form
# - set your form's endpoint url under 'formspree_action' below
# - upload the generated site to your server
# - test a dummy email yourself
# - you're done. Happy mailing!
#
# Enable the contact form by entering your Formspree.io endpoint url
#formspree_action = "https://formspree.io/sample/of/endpoint"
#contact_form_ajax = false

# Formspree form supports Google reCAPTCHA Key (type v2).
# If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
#
# By default, Formspree use a redirect page for recaptcha widget.
# If you use a recaptcha widget in your contact page, you should do next steps.
# (if you don't want, skip these steps)
#
#   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
#   2. select reCAPTCHA v2 and checkbox widget type.
#   3. remember site key and secret key.
#   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
#   5. change `enableRecaptchaInContactForm` is to true
#   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
#
enableRecaptchaInContactForm = false
googleRecaptchaKey = "site_key_for_google_recaptcha"

about_us = "Altamente Capaces"
copyright = "Copyright 2025 (c), Altamente Capaces. As an Amazon Associate, I earn from qualifying purchases."

# Format dates with Go's time formatting
date_format = "January 2, 2006"

dropdown_mouse_over = false

disabled_logo = false
logo_text = "Logotipo"

logo = "/logo.png"
logo_small = "/logo.png"
# contact_url = "/contactar"
address = """<p class="text-uppercase"></p>"""

[permalinks]
blog = "/blog/:year/:month/:day/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
categories = false
tags = true
search = false

[params.carouselCustomers]
items = 6
auto_play = true
slide_speed = 2000
pagination_speed = 1000

[params.carouselTestimonials]
items = 4
auto_play = true
slide_speed = 2000
pagination_speed = 1000

[params.carouselHomepage]
# All carousel items are defined in their own files. You can find example items
# at 'exampleSite/data/carousel'.
# For more information take a look at the README.
enable = true
auto_play = true
slide_speed = 2000
pagination_speed = 1000

[params.features]
enable = true
cols = 3          # Default: 3, Available values 2,3,4,6
# All features are defined in their own files. You can find example items
# at 'exampleSite/data/features'.
# For more information take a look at the README.

[params.testimonials]
enable = true
# All testimonials are defined in their own files. You can find example items
# at 'exampleSite/data/testimonials'.
# For more information take a look at the README.
title = "Falsos mitos"
subtitle = "Las Altas Capacidades están rodeadas de mitos que las perjudican... ¡conoce algunos y evítalos!"

#[params.see_more]
#enable = true
#icon = "fa-solid fa-couch"
#title = "¿Quieres encontrar un lugar para descansar rodeado de historia y de actividades al alcance de tu mano?"
#subtitle = "¡Has encontrado el lugar que buscabas!"
#link_url = "/contactar"
#link_text = "¡Contacta con nosotros!"

[params.clients]
enable = false
# All clients are defined in their own files. You can find example items
# at 'exampleSite/data/clients'.
# For more information take a look at the README.
title = "Our Clients"
subtitle = ""

[params.recent_posts]
enable = true
title = "De nuestro blog"
subtitle = "Aquí tienes algunos de nuestros artículos en el blog"
hide_summary = false

[params.footer.recent_posts]
enable = true

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[menu]

# Main menu
[[menu.main]]
name = "Inicio"
identifier = "menu.home"
url = "/"
weight = 1
#
# [[menu.main]]
# name = "Casa Isabel"
# identifier = "menu.casa"
# url = "/img/tinajas.jpg"
# weight = 3
#
# [[menu.main]]
# name = "La Casa"
# identifier = "section.shortcodes"
# url = ""
# weight = 1
# parent = "menu.casa"
# post = 1
#
# [[menu.main]]
# name = "Salon"
# url = "/salon"
# weight = 2
# parent = "section.shortcodes"
#
# [[menu.main]]
# name = "Habitaciones"
# url = "/habitaciones"
# weight = 3
# parent = "section.shortcodes"
#
# [[menu.main]]
# name = "Cocina"
# url = "/cocina"
# weight = 4
# parent = "section.shortcodes"
#
# [[menu.main]]
# name = "Terraza"
# url = "/terraza"
# weight = 5
# parent = "section.shortcodes"
#
# [[menu.main]]
# name = "Cómo llegar"
# url = "/llegar"
# weight = 6
# parent = "section.shortcodes"
#
# [[menu.main]]
# name = "Servicios"
# url = "/servicios"
# weight = 7
# parent = "section.shortcodes"
#
#
# [[menu.main]]
# name = "Normas"
# url = "/normas"
# weight = 8
# parent = "section.shortcodes"
#
#
#
# [[menu.main]]
# name = "Conócenos"
# url = "/acerca"
# weight = 9
# parent = "section.shortcodes"
#
#
# [[menu.main]]
# name = "Ocio"
# identifier = "menu.portfolio"
# url = "/img/entorno/albentosa.jpg"
# weight = 3
#
# [[menu.main]]
# name = "Ocio"
# identifier = "section.portfolio"
# url = ""
# weight = 1
# parent = "menu.portfolio"
# post = 1
#
# [[menu.main]]
# name = "El entorno"
# url = "/entorno"
# weight = 1
# parent = "section.portfolio"
#
#
# [[menu.main]]
# name = "Actividades"
# url = "/actividades"
# weight = 2
# parent = "section.portfolio"
#
# [[menu.main]]
# name = "Gastronomía"
# url = "/gastronomia"
# weight = 3
# parent = "section.portfolio"
#
# [[menu.main]]
# name = "Los pueblos más bonitos para visitar"
# url = "/pueblosbonitos"
# weight = 4
# parent = "section.portfolio"
#
# [[menu.main]]
# name = "Teruel"
# url = "/teruel"
# weight = 5
# parent = "section.portfolio"
#
#
# [[menu.main]]
# name = "Albentosa"
# url = "/albentosa"
# weight = 6
# parent = "section.portfolio"
#

[[menu.main]]
name = "Blog"
identifier = "menu.blog"
url = "/blog/"
weight = 4

[[menu.main]]
name = "Bibliografía"
identifier = "menu.book"
url = "/bibliografia/"
weight = 5

[[menu.main]]
name = "P+F"
identifier = "menu.faq"
url = "/faq/"
weight = 6

# [[menu.main]]
# identifier = "contact"
# name = "Contactar"
# url = "/contactar/"
# weight = 7

# Enable or disable top bar with social icons
[params.topbar]
enable = false
text = """"""

# Top bar social links menu
#
# [[menu.topbar]]
# weight = 1
# name = "Whatsapp"
# url = "https://wa.me/"
# pre = "<i class='fa-brands fa-2x fa-whatsapp'></i>"
#
# [[menu.topbar]]
#     weight = 2
#     name = "Instagram"
#     url = "http://instagram.com/"
#     pre = "<i class='fab fa-2x fa-instagram'></i>"
#
#
#
# [[menu.topbar]]
# weight = 3
# name = "Teléfono"
# url = "tel:+33"
# pre = "<i class='fas fa-2x fa-phone'></i>"
#
#
# [[menu.topbar]]
# weight = 4
# name = "Email"
# url = "mailto:info@altamentecapaces.org"
# pre = "<i class='fas fa-2x fa-envelope'></i>"
#
# [[menu.topbar]]
# weight = 5
# name = "Mapa"
# url = "/llegar"
# pre = "<i class='fa-2x fa-solid fa-map-marker'> </i>"
# #
#
#
#
#
